name: compose-test

services:
  frontend:
    build: ./landing
    ports:
      - "3129:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./api
    ports:
      - "3138:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: formulario_db
      
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    ports:
      - "9165:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formulario_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
