version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db
    networks:
      - tot-network

  landing:
    build: ./landing
    ports:
      - ":80"
    networks:
      - tot-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tot-network

volumes:
  dbdata:

networks:
  tot-network:
    driver: bridge
